name: Build saikpr/caddy-cloudflare

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
            docker buildx build --push \
            --tag saikpr/caddy-cloudflare:latest \
            --platform linux/amd64,linux/arm64 .